### PR TITLE
Added Knife Distance

### PR DESCRIPTION
**Pull request by EIonv**
Made WipeYVelocityToZeroIfHeadHitCeiling() function work, just collision with ceilings is a bit wonky.

### CODE REVIEW

**Comment by livinamuk** [comment]
Cheers! I'm surpised you managed to figure out the debug menu maze, great work! I started merging your light additions by hand but then realized it's quite a big job because all the indirect lighting compute structures need to be recalculated and I've gotta do a day on my real job today. I'll get to it soon. Thanks again, I appreciate the contributions!

**Comment by EIonv** [comment]
I completely just messed it up, but it took me a bit of time to figure out what was going on. But overall I enjoy going through it and seeing what I am able to add in. Take your time mine man, I am in no rush. and Your welcome, glad to have helped even with the little additions, my bad for the mistake again I didn't know resolving conflicts would've deleted the files.
Also, If I have to make another pull request for the missing data let me know!

**Comment by livinamuk** [comment]
Lucky I copied your code already cause it looks you deleted your commits? 

Cheers for checking out the `WipeYVelocityToZeroIfHeadHitCeiling()`. That is definitely something that needs addressing. It's not an option to rely on the y height of ceiling object because there will be other things the players head can collide with. It needs to be based off the actual PhysX world. 

It might be possible to do the inverse of what I'm doing for the `_isGrounded` check within `SetPlayerGroundedStates()` in Scene.cpp. It checks the character controller collision reports to see if the normal of the hit surface is *mostly* facing up, if so then the player capsule is touching the ground (or the top surface of the couch). Perhaps if the hit normal is mostly facing down then `_yVelocity` can simply be set to 0? The height of player caspsule will likely need to be increased to make this work properly, and that maybe introduce other issues, but if you're looking for something to play about with by all means take a look! 

Also if you don't know, pressing B cycles the different PhysX collision types, you want the one that is light blue, that shows the collision world and the player capsules. I'd commented out ceilings from being part of the physics world, but I've added them back in now and pushed the commit.

It'll be useful to switch to split screen with V to see the capsule size from the other players perspective. Unfortunately there is a PhysX bug where the actual capsule lines they give me for rendering do NOT reflect the actual capsule size in the PhysX world, which is a big reason for why I've been putting this off. It's hard to test when the capsule size you see is a lie. Still, it will be helpful to see from the other players perspective regardless. You can switch player with C.

The goal is to make the `_yVelocity` set to 0 when the player head hits a ceiling, and to never allow their head to clip through the roof. Ignore crouching for now, because that requries changing the capsule size during crouch and is its own kettle of worms.

Appolgies for the walls of text above, I would have wrote something shorter but I didn't have the time.

**Comment by livinamuk** [comment]
Also pressing the ~ key toggles debug text, and you can add to it at around line 700 in Renderer.cpp

**Comment by livinamuk** [comment]
If you do make a start on this, I think the best way to test it is to increase the player jump strength, it's line 224 in Player.cpp. Currently it's `4.75f` but making it `10.0f` would be helpful. I'd ignore the capsule height at first, and just try get it so when the capsule hits the roof it instantly sets the `_yVelocity` to 0, pressing ~ will display the `_yVelocity` also.

**Comment by EIonv** [comment]
My apologies for that, I am still not sure how I managed todo that

This may seem like a really stupid suggestion, But is it possible to add like a big box that is "Air" and making that box transparent and no collided in order to check if the player is just touching air.  and then check if the player is touching like a floor,ceiling,or wall. 
I have no idea how much much performance you lose so I had waited to ask this, I've been trying to figure out how to make it set the `yVelocity` to `0` but I haven't had any lucky yet.

I am not to sure, but it seems like it probably would be killing performance just for a big box to be used for Air.

Thank you for also pointing me towards the right direction, I was able to make it where it set the `yVelocity` to `0` but I froze above the ceiling instead of below. Just a bit stuck for right now.
and I am happy that you gave me that that walls of text cause it gave me some references where to look as I am not super familiar with the code yet.

**Pull request closed without merging**
